version: "3.9"

services:

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "9000:9000"
    env_file:
      - .env

  streamlit:
    build:
      context: .
      dockerfile: Dockerfile.streamlit
    ports:
      - "8501:8501"
    depends_on:
      - backend
    environment:
      MCP_URL: http://backend:9000