from typing import List, Dict, Any, Optional
from pydantic import BaseModel, Field



class NLQueryRequest(BaseModel):
    """
    Natural language question asked by the user.
    """
    question: str = Field(
        ...,
        min_length=3,
        max_length=1000,
        description="Natural language question about the database",
        example="What is the total sales revenue last month?",
    )




class SQLQuery(BaseModel):
    """
    SQL generated by the LLM (SELECT only).
    This is NOT directly executed without validation.
    """
    sql: str = Field(
        ...,
        description="Generated SQL query (read-only, SELECT only)",
        example=(
            "SELECT SUM(NetAmount) AS total_revenue "
            "FROM dbo.QBS_SighCast_Sales"
        ),
    )



class QueryResult(BaseModel):
    """
    Raw database result returned after SQL execution.
    """
    columns: List[str] = Field(
        ...,
        description="Column names returned from the database",
    )
    rows: List[Dict[str, Any]] = Field(
        ...,
        description="Result rows (list of dictionaries)",
    )
    row_count: int = Field(
        ...,
        description="Total number of rows returned",
        example=120,
    )



class NLQueryResponse(BaseModel):
    """
    Final response shown to the user.
    """
    question: str = Field(
        ...,
        description="Original user question",
    )
    answer: str = Field(
        ...,
        description="Natural language answer derived from the SQL result",
        example="Total sales revenue last month was 3.2 million EGP.",
    )
    sql: Optional[str] = Field(
        None,
        description="SQL used to answer the question (optional, debug mode only)",
    )
    preview_rows: Optional[List[Dict[str, Any]]] = Field(
        None,
        description="Preview of result rows (optional, limited)",
    )




class ErrorResponse(BaseModel):
    """
    Standard error response.
    """
    error_code: str = Field(
        ...,
        example="SECURITY_VIOLATION",
    )
    message: str = Field(
        ...,
        example="Your request violates security rules.",
    )
    context: Dict[str, Any] = Field(
        ...,
        description="Additional error context (safe metadata only)",
        example={"keyword": "drop"},
    )